//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("JobeetCSharpModel", "FK_Job_Category", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Jobeet.Models.Category), "Job", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Jobeet.Models.Job), true)]
[assembly: EdmRelationshipAttribute("JobeetCSharpModel", "CategoryAffiliate", "Affiliate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Jobeet.Models.Affiliate), "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Jobeet.Models.Category))]

#endregion

namespace Jobeet.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class JobeetCSharpEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new JobeetCSharpEntities object using the connection string found in the 'JobeetCSharpEntities' section of the application configuration file.
        /// </summary>
        public JobeetCSharpEntities() : base("name=JobeetCSharpEntities", "JobeetCSharpEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JobeetCSharpEntities object.
        /// </summary>
        public JobeetCSharpEntities(string connectionString) : base(connectionString, "JobeetCSharpEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JobeetCSharpEntities object.
        /// </summary>
        public JobeetCSharpEntities(EntityConnection connection) : base(connection, "JobeetCSharpEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Affiliate> Affiliate
        {
            get
            {
                if ((_Affiliate == null))
                {
                    _Affiliate = base.CreateObjectSet<Affiliate>("Affiliate");
                }
                return _Affiliate;
            }
        }
        private ObjectSet<Affiliate> _Affiliate;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Category
        {
            get
            {
                if ((_Category == null))
                {
                    _Category = base.CreateObjectSet<Category>("Category");
                }
                return _Category;
            }
        }
        private ObjectSet<Category> _Category;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Job> Job
        {
            get
            {
                if ((_Job == null))
                {
                    _Job = base.CreateObjectSet<Job>("Job");
                }
                return _Job;
            }
        }
        private ObjectSet<Job> _Job;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Affiliate EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAffiliate(Affiliate affiliate)
        {
            base.AddObject("Affiliate", affiliate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Category EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategory(Category category)
        {
            base.AddObject("Category", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Job EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToJob(Job job)
        {
            base.AddObject("Job", job);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public int ResetDefaultCategories()
        {
            return base.ExecuteFunction("ResetDefaultCategories");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JobeetCSharpModel", Name="Affiliate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Affiliate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Affiliate object.
        /// </summary>
        /// <param name="affiliateId">Initial value of the AffiliateId property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="token">Initial value of the Token property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static Affiliate CreateAffiliate(global::System.Int32 affiliateId, global::System.String url, global::System.String email, global::System.String token, global::System.Boolean isActive)
        {
            Affiliate affiliate = new Affiliate();
            affiliate.AffiliateId = affiliateId;
            affiliate.Url = url;
            affiliate.Email = email;
            affiliate.Token = token;
            affiliate.IsActive = isActive;
            return affiliate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AffiliateId
        {
            get
            {
                return _AffiliateId;
            }
            set
            {
                if (_AffiliateId != value)
                {
                    OnAffiliateIdChanging(value);
                    ReportPropertyChanging("AffiliateId");
                    _AffiliateId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AffiliateId");
                    OnAffiliateIdChanged();
                }
            }
        }
        private global::System.Int32 _AffiliateId;
        partial void OnAffiliateIdChanging(global::System.Int32 value);
        partial void OnAffiliateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Token
        {
            get
            {
                return _Token;
            }
            set
            {
                OnTokenChanging(value);
                ReportPropertyChanging("Token");
                _Token = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Token");
                OnTokenChanged();
            }
        }
        private global::System.String _Token;
        partial void OnTokenChanging(global::System.String value);
        partial void OnTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JobeetCSharpModel", "CategoryAffiliate", "Category")]
        public EntityCollection<Category> Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Category>("JobeetCSharpModel.CategoryAffiliate", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Category>("JobeetCSharpModel.CategoryAffiliate", "Category", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JobeetCSharpModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="slug">Initial value of the Slug property.</param>
        public static Category CreateCategory(global::System.Int32 categoryId, global::System.String name, global::System.String slug)
        {
            Category category = new Category();
            category.CategoryId = categoryId;
            category.Name = name;
            category.Slug = slug;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                if (_CategoryId != value)
                {
                    OnCategoryIdChanging(value);
                    ReportPropertyChanging("CategoryId");
                    _CategoryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryId");
                    OnCategoryIdChanged();
                }
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Slug
        {
            get
            {
                return _Slug;
            }
            set
            {
                OnSlugChanging(value);
                ReportPropertyChanging("Slug");
                _Slug = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Slug");
                OnSlugChanged();
            }
        }
        private global::System.String _Slug;
        partial void OnSlugChanging(global::System.String value);
        partial void OnSlugChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JobeetCSharpModel", "FK_Job_Category", "Job")]
        public EntityCollection<Job> Job
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Job>("JobeetCSharpModel.FK_Job_Category", "Job");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Job>("JobeetCSharpModel.FK_Job_Category", "Job", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JobeetCSharpModel", "CategoryAffiliate", "Affiliate")]
        public EntityCollection<Affiliate> Affiliate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Affiliate>("JobeetCSharpModel.CategoryAffiliate", "Affiliate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Affiliate>("JobeetCSharpModel.CategoryAffiliate", "Affiliate", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JobeetCSharpModel", Name="Job")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Job : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Job object.
        /// </summary>
        /// <param name="jobId">Initial value of the JobId property.</param>
        /// <param name="cateroryId">Initial value of the CateroryId property.</param>
        /// <param name="company">Initial value of the Company property.</param>
        /// <param name="position">Initial value of the Position property.</param>
        /// <param name="location">Initial value of the Location property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="howToApply">Initial value of the HowToApply property.</param>
        /// <param name="token">Initial value of the Token property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="expiresAt">Initial value of the ExpiresAt property.</param>
        /// <param name="createAt">Initial value of the CreateAt property.</param>
        /// <param name="updateAt">Initial value of the UpdateAt property.</param>
        public static Job CreateJob(global::System.Int32 jobId, global::System.Int32 cateroryId, global::System.String company, global::System.String position, global::System.String location, global::System.String description, global::System.String howToApply, global::System.String token, global::System.String email, global::System.DateTime expiresAt, global::System.DateTime createAt, global::System.DateTime updateAt)
        {
            Job job = new Job();
            job.JobId = jobId;
            job.CateroryId = cateroryId;
            job.Company = company;
            job.Position = position;
            job.Location = location;
            job.Description = description;
            job.HowToApply = howToApply;
            job.Token = token;
            job.Email = email;
            job.ExpiresAt = expiresAt;
            job.CreateAt = createAt;
            job.UpdateAt = updateAt;
            return job;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 JobId
        {
            get
            {
                return _JobId;
            }
            set
            {
                if (_JobId != value)
                {
                    OnJobIdChanging(value);
                    ReportPropertyChanging("JobId");
                    _JobId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("JobId");
                    OnJobIdChanged();
                }
            }
        }
        private global::System.Int32 _JobId;
        partial void OnJobIdChanging(global::System.Int32 value);
        partial void OnJobIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CateroryId
        {
            get
            {
                return _CateroryId;
            }
            set
            {
                OnCateroryIdChanging(value);
                ReportPropertyChanging("CateroryId");
                _CateroryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CateroryId");
                OnCateroryIdChanged();
            }
        }
        private global::System.Int32 _CateroryId;
        partial void OnCateroryIdChanging(global::System.Int32 value);
        partial void OnCateroryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Company
        {
            get
            {
                return _Company;
            }
            set
            {
                OnCompanyChanging(value);
                ReportPropertyChanging("Company");
                _Company = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Company");
                OnCompanyChanged();
            }
        }
        private global::System.String _Company;
        partial void OnCompanyChanging(global::System.String value);
        partial void OnCompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Logo
        {
            get
            {
                return _Logo;
            }
            set
            {
                OnLogoChanging(value);
                ReportPropertyChanging("Logo");
                _Logo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Logo");
                OnLogoChanged();
            }
        }
        private global::System.String _Logo;
        partial void OnLogoChanging(global::System.String value);
        partial void OnLogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private global::System.String _Position;
        partial void OnPositionChanging(global::System.String value);
        partial void OnPositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HowToApply
        {
            get
            {
                return _HowToApply;
            }
            set
            {
                OnHowToApplyChanging(value);
                ReportPropertyChanging("HowToApply");
                _HowToApply = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HowToApply");
                OnHowToApplyChanged();
            }
        }
        private global::System.String _HowToApply;
        partial void OnHowToApplyChanging(global::System.String value);
        partial void OnHowToApplyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Token
        {
            get
            {
                return _Token;
            }
            set
            {
                OnTokenChanging(value);
                ReportPropertyChanging("Token");
                _Token = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Token");
                OnTokenChanged();
            }
        }
        private global::System.String _Token;
        partial void OnTokenChanging(global::System.String value);
        partial void OnTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPublic
        {
            get
            {
                return _IsPublic;
            }
            set
            {
                OnIsPublicChanging(value);
                ReportPropertyChanging("IsPublic");
                _IsPublic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPublic");
                OnIsPublicChanged();
            }
        }
        private global::System.Boolean _IsPublic = true;
        partial void OnIsPublicChanging(global::System.Boolean value);
        partial void OnIsPublicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActivated
        {
            get
            {
                return _IsActivated;
            }
            set
            {
                OnIsActivatedChanging(value);
                ReportPropertyChanging("IsActivated");
                _IsActivated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActivated");
                OnIsActivatedChanged();
            }
        }
        private global::System.Boolean _IsActivated = false;
        partial void OnIsActivatedChanging(global::System.Boolean value);
        partial void OnIsActivatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExpiresAt
        {
            get
            {
                return _ExpiresAt;
            }
            set
            {
                OnExpiresAtChanging(value);
                ReportPropertyChanging("ExpiresAt");
                _ExpiresAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpiresAt");
                OnExpiresAtChanged();
            }
        }
        private global::System.DateTime _ExpiresAt;
        partial void OnExpiresAtChanging(global::System.DateTime value);
        partial void OnExpiresAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateAt
        {
            get
            {
                return _CreateAt;
            }
            set
            {
                OnCreateAtChanging(value);
                ReportPropertyChanging("CreateAt");
                _CreateAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateAt");
                OnCreateAtChanged();
            }
        }
        private global::System.DateTime _CreateAt;
        partial void OnCreateAtChanging(global::System.DateTime value);
        partial void OnCreateAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdateAt
        {
            get
            {
                return _UpdateAt;
            }
            set
            {
                OnUpdateAtChanging(value);
                ReportPropertyChanging("UpdateAt");
                _UpdateAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateAt");
                OnUpdateAtChanged();
            }
        }
        private global::System.DateTime _UpdateAt;
        partial void OnUpdateAtChanging(global::System.DateTime value);
        partial void OnUpdateAtChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JobeetCSharpModel", "FK_Job_Category", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("JobeetCSharpModel.FK_Job_Category", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("JobeetCSharpModel.FK_Job_Category", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("JobeetCSharpModel.FK_Job_Category", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("JobeetCSharpModel.FK_Job_Category", "Category", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
